"""create movies table
Revision ID: d2256269a42b
Revises: d996f60b597c
Create Date: 2021-02-20 23:02:16.982098
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2256269a42b'
down_revision = 'd996f60b597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rated', sa.String(length=10), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=250), nullable=True),
    sa.Column('plot', sa.String(length=750), nullable=True),
    sa.Column('country', sa.String(length=15), nullable=True),
    sa.Column('awards', sa.String(length=250), nullable=True),
    sa.Column('poster', sa.String(length=250), nullable=True),
    sa.Column('imdb_rating', sa.String(length=5), nullable=True),
    sa.Column('imdb_id', sa.String(length=15), nullable=True),
    sa.Column('production', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('streaming_app_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['streaming_app_id'], ['streaming_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
