name: Tests

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DATABASE_DRIVER: memory
    services:
      postgres:
        image: postgres:13.3-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: movies_freak_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: install
        run: yarn install

      - name: migrate
        run: yarn migrate:ci

      - name: test
        run: yarn test:ci
